### ISSUE TITLE
volume driver errors creating volume

### ISSUE THREAD

**Issue by seertenedos** [srgl/backer#3]
setup just following readme but volumes done work. error from syslog for create and mount of volume from docker compose

```
seer@portable:/sm/temp/backup$ tail -n 1050 /var/log/syslog | grep docker
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Get, {\"Name\":\"backup_testing\"}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="Error processing action VolumeDriver.Get: Error: Volume backup_testing doesn't exist" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at /app/src/plugin.js:166:26" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at /app/node_modules/async-lock/lib/index.js:125:12" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at AsyncLock._promiseTry (/app/node_modules/async-lock/lib/index.js:249:31)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at exec (/app/node_modules/async-lock/lib/index.js:124:9)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at AsyncLock.acquire (/app/node_modules/async-lock/lib/index.js:140:3)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at Plugin.get (/app/src/plugin.js:164:22)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at Plugin.handler (/app/src/plugin.js:44:38)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at processTicksAndRejections (internal/process/task_queues.js:89:5)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Capabilities, {}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Get, {\"Name\":\"backup_testing\"}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="Error processing action VolumeDriver.Get: Error: Volume backup_testing doesn't exist" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at /app/src/plugin.js:166:26" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at /app/node_modules/async-lock/lib/index.js:125:12" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at AsyncLock._promiseTry (/app/node_modules/async-lock/lib/index.js:249:31)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at exec (/app/node_modules/async-lock/lib/index.js:124:9)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at AsyncLock.acquire (/app/node_modules/async-lock/lib/index.js:140:3)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at Plugin.get (/app/src/plugin.js:164:22)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at Plugin.handler (/app/src/plugin.js:44:38)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=error msg="    at processTicksAndRejections (internal/process/task_queues.js:89:5)" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Create, {\"Name\":\"backup_testing\",\"Opts\":{\"backup_schedule\":\"0 1 * * *\",\"env_B2_ACCOUNT_ID\":\"xxx\",\"env_B2_ACCOUNT_KEY\":\"xxx\",\"env_restic_password\":\"testing\",\"env_restic_repository\":\"b2:xxx:/download\",\"forget_policy\":\"l7 w30\",\"forget_schedule\":\"0 1 * * 0\",\"restore\":\"n\",\"size\":\"25M\"}}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Capabilities, {}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Get, {\"Name\":\"backup_testing\"}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Capabilities, {}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Get, {\"Name\":\"backup_testing\"}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Capabilities, {}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823
Nov 18 05:59:51 portable dockerd[1836]: time="2019-11-18T05:59:51+11:00" level=info msg="Action VolumeDriver.Mount, {\"Name\":\"backup_testing\",\"ID\":\"a00373f0f0209c560670a8fd3c3ae23f4485b08813a6e2c2852baf3c3b9a68c2\"}" plugin=acbc33eba7ead383228238fcdfdf88456a07b3de07f2fce92bc8592128d70823

```

**Comment by seertenedos** [comment]
I managed to solve it as it seems it worked in the logs above. before that i was pointing to a remote store that was not initalised

One strange thing is i found the volume itself and a few other working folders stored under /var/lib/docker/plugins.  I assume the backer, storage and tmp folders are from backer. and the volume itself was in the backer folder. i know some storage volumes like sshfs let you specify the directory the data is stored on the server. That may be a good idea here as this may not work well for large volumes and it seems strages for volumes to be in a plugins folder to me at least.
